apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  # Prometheus
  - prometheus/prometheus-config.yaml
  - prometheus/prometheus-deployment.yaml
  - prometheus/prometheus-service.yaml
  
  # Grafana
  - grafana/grafana-config.yaml
  - grafana/grafana-dashboard.yaml
  - grafana/grafana-deployment.yaml
  - grafana/grafana-service.yaml

commonLabels:
  project: devops-final-lab
  component: monitoring
